[project]
name = "flashroboorch"
version = "0.1.0"
description = "( Robot Orchestra, 机器人像乐队一样协作) 包含协作机器人, 人形双臂机器人和工业机器人的多机器人编排演示demo，机器人执行同步操作以实现具体长任务。"
readme = "README.md"
requires-python = ">=3.11, <3.12"
dependencies = [
    "ampl",
    "fastapi==0.123.5",
    "flash-models",
    "numpy==2.2.6",
    "uvicorn==0.38",
    "viser==1.0.16",
    "websockets>=12.0",
    "yourdfpy==0.0.58",
]

[tool.uv.sources]
flash-models = { git = "ssh://git@gitlab.roboticplus.com/flash/flashdata.git", rev = "f41b4d9f" }
ampl = { path = "third_party/ampl-0.0.17-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/robots_orchestra"]
